### ISSUE TITLE
Error when doing "run 3"

### ISSUE THREAD

**Issue by malicorX** [SaturnCassini/gpt4all_generative_agents#5]
Hi,

first of all, great work, and thanks for sharing !

i get an error though when i run this, here is what i do:

[...]
E:\AI\gpt4all_generative_agents>gpt4all_generative_agents\Scripts\activate
cd environment/frontend_server
python manage.py runserver

http://127.0.0.1:8000/

cd reverie/backend_server
python reverie.py

-> name: base_the_ville_isabella_maria_klaus
-> simulationname: test-simulation
-> run 3
[...]

and this is the error:

Name: John Doe
Age: 32
Backstory: John is a software engineer who works from home and enjoys playing video games in his free time. He is always looking for ways to improve himself and learn new things.
Personality: intelligent, analytical, curious
Location: John lives in an apartment with his cat named Whiskers. His current project is developing a virtual reality game that simulates a space exploration experience.
Currently: John plans on playing video games after work and spending time with Whiskers. He also wants to start learning programming languages again.
Daily plan requirement: John works from home, so he doesn't have any specific daily tasks or routines. However, he tries to be productive by setting aside time for work and personal projects.
-==- -==- -==-
Traceback (most recent call last):
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\reverie.py", line 468, in open_server
    rs.start_server(int_count)
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\reverie.py", line 379, in start_server
    next_tile, pronunciatio, description = persona.move(
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\persona\persona.py", line 222, in move
    plan = self.plan(maze, personas, new_day, retrieved)
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\persona\persona.py", line 148, in plan
    return plan(self, maze, personas, new_day, retrieved)
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\persona\cognitive_modules\plan.py", line 959, in plan
    _determine_action(persona, maze)
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\persona\cognitive_modules\plan.py", line 579, in _determine_action
    generate_task_decomp(persona, act_desp, act_dura))
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\persona\cognitive_modules\plan.py", line 164, in generate_task_decomp
    return run_gpt_prompt_task_decomp(persona, task, duration)[0]
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\persona\prompt_template\run_gpt_prompt.py", line 439, in run_gpt_prompt_task_decomp
    output = safe_generate_response(prompt, gpt_param, 5, get_fail_safe(),
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\persona\prompt_template\gpt_structure.py", line 257, in safe_generate_response
    return func_clean_up(curr_gpt_response, prompt=prompt)
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\persona\prompt_template\run_gpt_prompt.py", line 376, in __func_clean_up
    if task[-1] == ".":
IndexError: string index out of range
Error.

additionally it's computing reaaaally slow, even though i got a very fast computer (with a 4090 and a amd ryzen 9 7950x3d

help would be highly appreciated

**Comment by malicorX** [comment]
"fin" throws an error, too:

Enter option: fin
Traceback (most recent call last):
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\reverie.py", line 442, in open_server
    self.save()
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\reverie.py", line 187, in save
    persona.save(save_folder)
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\persona\persona.py", line 78, in save
    self.scratch.save(f_scratch)
  File "E:\AI\gpt4all_generative_agents\reverie\backend_server\persona\memory_structures\scratch.py", line 287, in save
    .strftime("%B %d, %Y, %H:%M:%S"))
AttributeError: 'NoneType' object has no attribute 'strftime'
Error.
