### ISSUE TITLE
 When I ran reverie.py, I encountered an error

### ISSUE THREAD

**Issue by snkzlg2024** [SaturnCassini/gpt4all_generative_agents#9]
F:\gpt4all_generative_agents\reverie\backend_server>python reverie.py
Traceback (most recent call last):
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1386, in getresponse
    response.begin()
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1386, in getresponse
    response.begin()
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\gpt4all_generative_agents\reverie\backend_server\reverie.py", line 36, in <module>
    from persona.persona import *
  File "F:\gpt4all_generative_agents\reverie\backend_server\persona\persona.py", line 23, in <module>
    from persona.cognitive_modules.perceive import *
  File "F:\gpt4all_generative_agents\reverie\backend_server\persona\cognitive_modules\perceive.py", line 12, in <module>    from persona.prompt_template.gpt_structure import *
  File "F:\gpt4all_generative_agents\reverie\backend_server\persona\prompt_template\gpt_structure.py", line 16, in <module>
    model = GPT4All(gpt4all_model)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt4all\gpt4all.py", line 235, in __init__
    self.config: ConfigType = self.retrieve_model(model_name, model_path=model_path, allow_download=allow_download, verbose=verbose)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt4all\gpt4all.py", line 310, in retrieve_model
    available_models = cls.list_models()
                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt4all\gpt4all.py", line 278, in list_models
    resp = requests.get("https://gpt4all.io/models/models3.json")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 724, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 724, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 265, in resolve_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by lzes** [comment]
Have you solved this problem?
